# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'Create Live' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Create Live
  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Performance'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  

end
